### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by Yaoyx** [Fudenberg-Research-Group/fastaFRiP#30]
**Questions**
- [ ] Q: are there technical covariates of FRiP for WT/Control samples?
        (e.g., exact antibody, instrument for sequencing, sequencing depth, fragment size, fraction of mapped reads,)
- [ ] Q: subsampling analysis on a deeply sequenced dataset: compute FRiP as a function of number of reads
- [ ] Q: show impact of samtools -q for FRiP
- [ ] Q: are there datasets with cohesin/CTCF through differentiation? does that change FRiP in an interesting way?
- [ ] Q:are we missing ChIPseqs for any useful papers, e.g. Bonev, Rao, Nora?

**Pipeline recommendations:**
- [ ] can antibody column be automatically generated from another column
- [ ] can compute spike-in from dumping bam rather than keeping sam around? is there a tool that can ditch the header
(grep -c -22 is somewhat suspicious as this might depend on number of chromosomes in the genome of interest)
- [ ] how should a user enter their own metadata, i.e. a non-GEO dataset?
- [ ] how does pipeline deal with optical duplications if GEO drops them anyways?
- [ ] should we be using wrappers for tools rather than the custom pre-specified conda environment? https://snakemake-wrappers.readthedocs.io/en/stable/
- [ ] are we properly using information from paired-end sequencing? read paper about macs2: https://www.biorxiv.org/content/10.1101/496521v1.full.pdf
- [ ] are there any things that ENCODE does that we should do? anything that we do that ENCODE forgets? https://docs.google.com/document/d/1lG_Rd7fnYgRpSIqrIfuVlAz2dW1VaSQThzk836Db99c/edit#heading=h.4fd6ehx9hkuj
- [ ] same question for the snakemake pipeline converted from nextflow: https://github.com/snakemake-workflows/chipseq/
- [ ] sync sample_name vs. sample 
- [x]  <img width="609" alt="image" src="https://github.com/user-attachments/assets/9af5e830-022b-4cfb-8659-7b7d9692fa07">

**Comment by Yaoyx** [comment]
**Code review**
- [x] Q: constants are often UPPERCASE, would some global variables be uppercase too? can check out a snakemake or python style guide
Ans: PEP 8 shows the conventions are about the same as those for functions.
